import { FiHome, FiUsers, FiLink2 } from "react-icons/fi";

export const USERS = [
  {
    id: "USR-001",
    name: "Ehizojie Ihayere",
    email: "ehizojie@scmcapital.com",
    roleName: "Technology Team",
    roleType: "Permanent",
    status: "Awaiting Approval" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "USR-002",
    name: "Ehizojie Ihayere",
    email: "ehizojie@scmcapital.com",
    roleName: "Technology Team",
    roleType: "Permanent",
    status: "Awaiting Approval" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "USR-003",
    name: "Ehizojie Ihayere",
    email: "ehizojie@scmcapital.com",
    roleName: "Technology Team",
    roleType: "Temporary",
    roleExpiry: "Expires March 12, 2026",
    status: "Active" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "USR-004",
    name: "Ehizojie Ihayere",
    email: "ehizojie@scmcapital.com",
    roleName: "Technology Team",
    roleType: "Temporary",
    roleExpiry: "Expires March 12, 2026",
    status: "Active" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "USR-005",
    name: "Ehizojie Ihayere",
    email: "ehizojie@scmcapital.com",
    roleName: "Technology Team",
    roleType: "Temporary",
    roleExpiry: "Expires March 12, 2026",
    status: "Deactivated" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "USR-006",
    name: "Ehizojie Ihayere",
    email: "ehizojie@scmcapital.com",
    roleName: "Technology Team",
    roleType: "Permanent",
    status: "Awaiting Approval" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "USR-007",
    name: "Ehizojie Ihayere",
    email: "ehizojie@scmcapital.com",
    roleName: "Technology Team",
    roleType: "Temporary",
    roleExpiry: "Expires March 12, 2026",
    status: "Deactivated" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "USR-008",
    name: "Ehizojie Ihayere",
    email: "ehizojie@scmcapital.com",
    roleName: "Technology Team",
    roleType: "Temporary",
    roleExpiry: "Expires March 12, 2026",
    status: "Active" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "USR-009",
    name: "Ehizojie Ihayere",
    email: "ehizojie@scmcapital.com",
    roleName: "Technology Team",
    roleType: "Temporary",
    roleExpiry: "Expires March 12, 2026",
    status: "Deactivated" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "USR-010",
    name: "Ehizojie Ihayere",
    email: "ehizojie@scmcapital.com",
    roleName: "Technology Team",
    roleType: "Temporary",
    roleExpiry: "Expires March 12, 2026",
    status: "Deactivated" as const,
    updated: "28/12/2025 13:32",
  },
];

export const ROLES = [
  {
    id: "ROLE-001",
    name: "Technology Team",
    description: "Description of role here",
    status: "Active" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "ROLE-002",
    name: "Technology Team",
    description: "Description of role here",
    status: "Active" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "ROLE-003",
    name: "Technology Team",
    description: "Description of role here",
    status: "Awaiting Approval" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "ROLE-004",
    name: "Technology Team",
    description: "Description of role here",
    status: "Awaiting Approval" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "ROLE-005",
    name: "Technology Team",
    description: "Description of role here",
    status: "Deactivated" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "ROLE-006",
    name: "Technology Team",
    description: "Description of role here",
    status: "Active" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "ROLE-007",
    name: "Technology Team",
    description: "Description of role here",
    status: "Deactivated" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "ROLE-008",
    name: "Technology Team",
    description: "Description of role here",
    status: "Awaiting Approval" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "ROLE-009",
    name: "Technology Team",
    description: "Description of role here",
    status: "Deactivated" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "ROLE-010",
    name: "Technology Team",
    description: "Description of role here",
    status: "Deactivated" as const,
    updated: "28/12/2025 13:32",
  },
];

export const DEPARTMENTS = [
  {
    id: "DEPT-001",
    name: "Technology Team",
    description: "Description of department here",
    members: 32,
    status: "Active" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "DEPT-002",
    name: "Technology Team",
    description: "Description of department here",
    members: 100,
    status: "Active" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "DEPT-003",
    name: "Technology Team",
    description: "Description of department here",
    members: 2,
    status: "Awaiting Approval" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "DEPT-004",
    name: "Technology Team",
    description: "Description of department here",
    members: 15,
    status: "Awaiting Approval" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "DEPT-005",
    name: "Technology Team",
    description: "Description of department here",
    members: 90,
    status: "Deactivated" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "DEPT-006",
    name: "Technology Team",
    description: "Description of department here",
    members: 100,
    status: "Active" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "DEPT-007",
    name: "Technology Team",
    description: "Description of department here",
    members: 2,
    status: "Deactivated" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "DEPT-008",
    name: "Technology Team",
    description: "Description of department here",
    members: 105,
    status: "Awaiting Approval" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "DEPT-009",
    name: "Technology Team",
    description: "Description of department here",
    members: 77,
    status: "Deactivated" as const,
    updated: "28/12/2025 13:32",
  },
  {
    id: "DEPT-010",
    name: "Technology Team",
    description: "Description of department here",
    members: 64,
    status: "Deactivated" as const,
    updated: "28/12/2025 13:32",
  },
];

export const USER_ROLE_SIDEBAR_ITEMS = [
  { icon: FiHome, label: "Overview", href: "#", isActive: true },
  { icon: FiUsers, label: "Create New User", href: "#" },
  { icon: FiUsers, label: "Create New Role", href: "#" },
  { icon: FiUsers, label: "Create Department", href: "#" },
];

export const STATS_CONFIG = [
  { label: "Active Users", value: "20" },
  { label: "Inactive Users", value: "20" },
];

export const PAGE_CONFIG = {
  title: "User & Role Management",
  itemsPerPage: 10,
};

export const getBreadcrumbs = (activeItem?: string) => [
  { label: "Dashboard", href: "/dashboard" },
  { label: "User & Role Management", href: "/dashboard/user-role-management" },
  ...(activeItem && activeItem !== "Overview" ? [{ label: activeItem }] : []),
];
