import { FiHome, FiUsers } from "react-icons/fi";

export const BLOG_SIDEBAR_ITEMS = [
  {
    icon: FiHome,
    label: "Overview",
    href: "/dashboard/blog-and-faqs",
  },
  {
    icon: FiUsers,
    label: "Create Blog Post",
    href: "/dashboard/blog-and-faqs/create-blog",
  },
  {
    icon: FiUsers,
    label: "Create FAQ",
    href: "/dashboard/blog-and-faqs/create-faq",
  },
];

export const BLOG_STATS_CONFIG = [
  {
    label: "All Blogs",
    value: "500",
  },
  {
    label: "Homepage Blogs",
    value: "20",
  },
  {
    label: "Product Blogs",
    value: "20",
  },
];

export const FAQ_STATS_CONFIG = [
  {
    label: "All FAQs",
    value: "20",
  },
  {
    label: "Homepage Blogs",
    value: "20",
  },
  {
    label: "Product Blogs",
    value: "20",
  },
];

export const PAGE_CONFIG = {
  title: "Blog & FAQs",
  itemsPerPage: 8,
};

export const BLOG_POSTS = [
  {
    id: "1",
    title: "Blog title here in two lines maximum, if more extend the...",
    description: "One line description of the blo...",
    author: "Iwinosa Omoregie",
    audience: "Blog Section",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Iwinosa Omoregie",
    status: "Active" as const,
    approverStatus: "Approved" as const,
    image: "/scmassetLogo.svg",
  },
  {
    id: "2",
    title: "Blog title in one line",
    description: "One line description of the blo...",
    author: "Iwinosa Omoregie",
    audience: "Homepage",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Omotolani Babajide",
    status: "Awaiting Approval" as const,
    approverStatus: "Awaiting Approval" as const,
    image: "/scmassetLogo.svg",
  },
  {
    id: "3",
    title: "Blog title here in two lines maximum, if more extend the...",
    description: "One line description of the blo...",
    author: "Iwinosa Omoregie",
    audience: "Product Page",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Omotolani Babajide",
    status: "Active" as const,
    approverStatus: "Approved" as const,
    image: "/scmassetLogo.svg",
  },
  {
    id: "4",
    title: "Blog title here in two lines maximum, if more extend the...",
    description: "One line description of the blo...",
    author: "Iwinosa Omoregie",
    audience: "Blog Section",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Iwinosa Omoregie",
    status: "Awaiting Approval" as const,
    approverStatus: "Awaiting Approval" as const,
    image: "/scmassetLogo.svg",
  },
  {
    id: "5",
    title: "Blog title in one line",
    description: "One line description of the blo...",
    author: "Iwinosa Omoregie",
    audience: "Blog Section",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Omotolani Babajide",
    status: "Awaiting Approval" as const,
    approverStatus: "Awaiting Approval" as const,
    image: "/scmassetLogo.svg",
  },
  {
    id: "6",
    title: "Blog title in one line",
    description: "One line description of the blo...",
    author: "Iwinosa Omoregie",
    audience: "Homepage",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Iwinosa Omoregie",
    status: "Active" as const,
    approverStatus: "Approved" as const,
    image: "/scmassetLogo.svg",
  },
  {
    id: "7",
    title: "Blog title here in two lines maximum, if more extend the...",
    description: "One line description of the blo...",
    author: "SCM Admin",
    audience: "Blog Section",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Iwinosa Omoregie",
    status: "Active" as const,
    approverStatus: "Approved" as const,
    image: "/scmassetLogo.svg",
  },
  {
    id: "8",
    title: "Blog title here in two lines maximum, if more extend the...",
    description: "One line description of the blo...",
    author: "SCM Admin",
    audience: "Blog Section",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Omotolani Babajide",
    status: "Awaiting Approval" as const,
    approverStatus: "Awaiting Approval" as const,
    image: "/scmassetLogo.svg",
  },
  {
    id: "9",
    title: "Blog title here in two lines maximum, if more extend the...",
    description: "One line description of the blo...",
    author: "Iwinosa Omoregie",
    audience: "Homepage",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Iwinosa Omoregie",
    status: "Active" as const,
    approverStatus: "Approved" as const,
    image: "/scmassetLogo.svg",
  },
  {
    id: "10",
    title: "Blog title here in two lines maximum, if more extend the...",
    description: "One line description of the blo...",
    author: "Iwinosa Omoregie",
    audience: "Blog Section",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Omotolani Babajide",
    status: "Active" as const,
    approverStatus: "Approved" as const,
    image: "/scmassetLogo.svg",
  },
];

export const FAQS = [
  {
    id: "1",
    title: "FAQ title here in two lines maximum, if more extend the...",
    description: "One line description of the faq description",
    author: "Iwinosa Omoregie",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Omotolani Babajide",
    status: "Active" as const,
    approverStatus: "Approved" as const,
  },
  {
    id: "2",
    title: "FAQ title in one line",
    description: "One line description of the faq description",
    author: "Iwinosa Omoregie",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Omotolani Babajide",
    status: "Awaiting Approval" as const,
    approverStatus: "Awaiting Approval" as const,
  },
  {
    id: "3",
    title: "FAQ title here in two lines maximum, if more extend the...",
    description: "One line description of the faq description",
    author: "Iwinosa Omoregie",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Iwinosa Omoregie",
    status: "Active" as const,
    approverStatus: "Approved" as const,
  },
  {
    id: "4",
    title: "FAQ title here in two lines maximum, if more extend the...",
    description: "One line description of the faq description",
    author: "Iwinosa Omoregie",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Iwinosa Omoregie",
    status: "Awaiting Approval" as const,
    approverStatus: "Awaiting Approval" as const,
  },
  {
    id: "5",
    title: "FAQ title in one line",
    description: "One line description of the faq description",
    author: "Iwinosa Omoregie",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Omotolani Babajide",
    status: "Awaiting Approval" as const,
    approverStatus: "Awaiting Approval" as const,
  },
  {
    id: "6",
    title: "FAQ title in one line",
    description: "One line description of the faq description",
    author: "Iwinosa Omoregie",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Iwinosa Omoregie",
    status: "Active" as const,
    approverStatus: "Approved" as const,
  },
  {
    id: "7",
    title: "FAQ title here in two lines maximum, if more extend the...",
    description: "One line description of the faq description",
    author: "SCM Admin",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Iwinosa Omoregie",
    status: "Active" as const,
    approverStatus: "Approved" as const,
  },
  {
    id: "8",
    title: "FAQ title here in two lines maximum, if more extend the...",
    description: "One line description of the faq description",
    author: "SCM Admin",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Omotolani Babajide",
    status: "Awaiting Approval" as const,
    approverStatus: "Awaiting Approval" as const,
  },
  {
    id: "9",
    title: "FAQ title here in two lines maximum, if more extend the...",
    description: "One line description of the faq description",
    author: "Iwinosa Omoregie",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Iwinosa Omoregie",
    status: "Active" as const,
    approverStatus: "Approved" as const,
  },
  {
    id: "10",
    title: "FAQ title here in two lines maximum, if more extend the...",
    description: "One line description of the faq description",
    author: "Iwinosa Omoregie",
    dateCreated: "28/12/2025 13:32",
    lastUpdated: "28/12/2025 13:32",
    lastUpdatedBy: "Omotolani Babajide",
    status: "Active" as const,
    approverStatus: "Approved" as const,
  },
];

export const getBreadcrumbs = (currentView: string) => [
  { label: "Dashboard", href: "/dashboard" },
  { label: "Blog & FAQs", href: "/dashboard/blog-and-faqs" },
  ...(currentView !== "Overview" ? [{ label: currentView }] : []),
];
